service: skeleton
owner: gendo
organization: gendo
description: Skeleton for Go services in GenDO platform
type: business
port: 8080

env:
  LOG_LEVEL: info
  SERVICE_VERSION: "1.0.0"
  METRICS_ENABLED: true
  HEALTH_CHECK_ENABLED: true

env.staging:
  LOG_LEVEL: debug

env.production:
  LOG_LEVEL: warn

dependencies:
  # Примеры зависимостей - раскомментируйте и настройте под ваш сервис
  
  # База данных
  # - type: database
  #   name: postgres
  #   version: 15
  #   port: 5432
  #   database: skeleton_db

  # Кэш
  # - type: cache
  #   name: redis
  #   version: 7.0
  #   port: 6379

  # Очередь сообщений
  # - type: queue
  #   name: rabbitmq
  #   version: 3.12
  #   port: 5672

  # Другой сервис
  # - type: service
  #   name: auth-service
  #   port: 8080
  #   path: /api/v1
