service: skeleton
owner: he110
env:
  LOG_LEVEL: info
env.local:
  LOG_LEVEL: debug
# env.prod:
#   Используй данную секцию для установки не чувствительных переменных окружения для продакшена
#   LOG_LEVEL: warning
# env.staging:
#   Используй данную секцию для установки не чувствительных переменных окружения для стэйджа
#   LOG_LEVEL: debug
dependencies:
  - type: database
    name: postgres
    version: 15
  - type: service
    name: auth
    