openapi: '3.1.0'
info:
  title: Restfull API
  version: '1.0'
servers:
  - url: https://api.restful-api.dev
paths:
  /objects/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  data:
                    type: object
                    additionalProperties: true
